server:
  port: 8088
spring:
  cloud:
    nacos:
      server-addr: 129.69.209.197:30008
      discovery:
        cluster-name: Stuttgart
#        namespace: haoran
  application:
    name: database-service
  datasource:
    dynamic:
      primary: master #set the default database: master
      strict: false #
      datasource:
        master:
          url: jdbc:postgresql://129.69.209.197:30414/lib?currentSchema=public&characterEncoding=UTF-8&allowMultiQueries=true
          username: postgres
          password: XvR7XF6nbt7OjCjMEENiROPo9J3yqIk3CfT1AJHKXSPxrFANnTZ9A3N2bU8pW4jj
          driver-class-name: org.postgresql.Driver #
        replica:
          url: jdbc:postgresql://129.69.209.197:31104/lib?currentSchema=public&characterEncoding=UTF-8
          username: postgres
          password: XvR7XF6nbt7OjCjMEENiROPo9J3yqIk3CfT1AJHKXSPxrFANnTZ9A3N2bU8pW4jj
          driver-class-name: org.postgresql.Driver
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://129.69.209.197:30526/reposcatalogdb?currentSchema=public&characterEncoding=UTF-8
#    username: postgres
#    password: root

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false   #
  global-config:
    db-config:
      update-strategy: ignored    #
