apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchengineservice
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      run: searchengineservice
  template:
    metadata:
      labels:
        run: searchengineservice
    spec:
      containers:
        - image: 0yhr0/searchengine-service:1.2.1
          name: searchengineservice
          ports:
            - containerPort: 8083
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: searchengineservice
  namespace: dev
spec:
  selector:
    run: searchengineservice
  type: NodePort
  sessionAffinity: ClientIP
  ports: # 端口信息
    - protocol: TCP
      port: 8083  # service端口
      targetPort: 8083 # pod端口
      nodePort: 31001 # 主机端口