server:
  port: 8083
spring:
  cloud:
    nacos:
      server-addr: 129.69.209.197:30008
      discovery:
        cluster-name: Stuttgart # 集群名称
  application:
    name: solr-service  #服务名称
  data:
    solr:
      host: http://129.69.209.197:30002/solr/testcore
