apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      run: userservice
  template:
    metadata:
      labels:
        run: userservice
    spec:
      containers:
        - image: 0yhr0/user-service:1.2.2
          name: userservice
          ports:
            - containerPort: 8080
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: userservice
  namespace: dev
spec:
  selector:
    run: userservice
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31002