apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
spec:
  storageClassName: nfs
  capacity:
    storage: 1500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs: 
    path: /mnt/nfs-mysql
    server: 129.69.209.197
