apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql2
  name: mysql
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
      nodePort: 31061
  type: NodePort
  selector:
    app: mysql2
